### ISSUE TITLE
Create API or library for competitors to easily grab >>1 feeds and feature vectors

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#124]
### Background / motivation

In predict-eth, we see that most competitors just use "what's convenient", which right now is basically just the past ETH price.

We also see that most competitors want to iterate on algorithms, and less on data.

It's much more rare to see them use _way_ more data, such as:
- CEX data: 40 exchanges x (o, h, l, c, v) x (raw data, AR, MA), liquidity pools, etc. Eg via ccxt + calculating AR,MA + more.
- DEX data: n exchanges x price, TVL in pools, volumes, etc.
- bridge data: for each time point, the flow of funds from location A --> B, for all different (A, B pairs). Where A & B can each be any CEX, DEX, wallet, or other

Imagine if the data above (or even a fraction of it) was super-convenient to predict-eth competitors?

This would greatly "up the game" among the competitors. Which would lead to greater accuracy numbers.

### TODO

Jaime has a starting point of the above data. Really just a fraction, but that's ok.

The TODO of this issue is to make that "starting point" of data super-convenient! (After which, we can keep tacking in more data.)

How: one or both of:
1. serve it up as a REST API. Like calling Binance API
2. have a pypi library, e.g. "data-agg" or "web3data". There's a single default command to get the data. Like using ccxt py lib.

Doing (1) means we have to run a server and it does the compute; user has very little work. Doing (2) means that the user has to do the install work, and then run the compute himself. Doing (3) means max flexibility to the user, and max work to us.
- Update: Christian, Jaime and Trent discussed: we'll do (1) to start. If it gets painful, we can switch to (2). 

Details on (1):
- Q: How to deploy? 
  - Options: (a) plain free REST API (b) Token-gate simple REST API with Ocean tech, charge small $ (3) Deploy as C2D-a;g   A: Christian/Jaime/Trent discussed this at length! 
   - Tradeoffs: (i) convenience to user / minimization of churn; (ii) implementation & maintenance effort; (iii) traction of Ocean usage / place for Data Farmers; (iiiv) feedback to evolve C2D tech 
   - Chosen: (a). Why: for here, the priority is (i)(ii). Jaime expects 1-2 weeks. Note that he's already ag Then we can get back to work on "accurate predict-ETH, $", which will eventually drive (iii)(iv)
- So, we'd run a server, on AWS or Azure
- Q: Py-based or JS-based server? 
- A: Py-based, so that it's more approachable to S2 team, and maintainable by them

**Comment by jfdelgad** [comment]
The ongoing work is [here](https://github.com/oceanprotocol/predict-eth-data-sources/tree/feat/ohlcv_data)

Added poetry to manage dependencies, cex data from top 20, volume (buy and sell) for the coins from the top 20 with pools in uniswap, and liquidity across time.

Working now in an unified endpoint to get formated onachain and off-chain data, should be done today or early tomorrow

**Comment by trentmc** [comment]
From @jfdelgad in [slack](https://oceanprotocol.slack.com/archives/C04PGGXJ60N/p1681138875237599):

----

The test version of the API is online now

https://predict-eth-data-sources.oceanprotocol.com/

You cna [sic] learn how to consume it using the Readme of the repo: https://github.com/oceanprotocol/predict-eth-data-sources

**Comment by trentmc** [comment]
Great!!

Suggestions to improve the README:
- Have two clearly-marked sections on how to use. (1) Using REST API on remote server. Make it dead-obvious so that all people have to do is copy & paste the curl command, without having to change any characters. Then give the endpoint documentation. (2) Local installation & usage.
- Replace <ocean_repo> with the actual name of the repo. 
- Remove the "$". People should be able to copy & paste, without having to remove characters.

General suggestions:
- predict-eth-data-sources.oceanprotocol.com is pretty long. I recommend something shorter, like "predict-eth-data.oceanprotocol.com" or even "pe.oceanprotocol.com"

Question: 
- Re: "This API uses Transpose under the hood, so an API KEY is needed for the application to run. You can either set up the environment variable TRANSPOSE_API_KEY before"
- Is this only needed for local, or for remote too?

**Comment by trentmc** [comment]
This is live at https://predict-eth-data.oceanprotocol.com/
