### ISSUE TITLE
Tweak submit readme so connecting to mumbai happens before publishing the asset

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/predict-eth#146]
### Problem
If you follow the tutorial, the user should complete getting test Matic + OCEAN in step 1.4

However, when publishing the asset and obtaining the `ocean` object to publish, we don't emphasize the mumbai network connection until the next section (judging).

### Solution
- [ ] Reorganize README slightly so user connects to polygon-test before publishing the asset.

**Comment by trentmc** [comment]
done

**Comment by trentmc** [comment]
done
