### ISSUE TITLE
add the solution to the coincurve and wheel error when installing ocean.py

### ISSUE THREAD

**Issue by juanpablovs** [oceanprotocol/predict-eth#19]
many users (including myself) have experienced problems when using pip to install the dependencies of ocean.py

specifically there is a relatively frequent error that is related to the coincurve package and wheel

in these situations (that again are very frequent and can be very frustrating) if they run this command first and after that they execute pip, the installation will work correctly

sudo apt-get install -y autoconf automake build-essential libffi-dev libtool pkg-config python3-dev

**Comment by trentmc** [comment]
not an issue with new ocean.py

**Comment by bballamudi** [comment]
Thanks @juanpablovs. I was stuck with this issue for like half hour and your solution worked.
