### ISSUE TITLE
to discuss with the team -> challenges = generations of improvements to get to a full prediction model

### ISSUE THREAD

**Issue by juanpablovs** [oceanprotocol/predict-eth#20]
Our objective is to get notoriety. To have hundreds of submissions and become a source of truth for DeFi traders, among other things

I would suggest that to help DeFi traders make money we need a full comprehensive model of trading.

A comprehensive model of trading includes useful libraries, good data, sound trading strategies, effective backtesting strategies, etc.

We are well positioned and we have different challenges of predict-Eth. So I would like to suggest that we first agree on all that would be needed (a list of our model of trading) and then focus on one theme per challenge. May be we can even repeat the theme down the line to reinforce it (for example, backtesting strategies second edition, etc.)

In my experience a competition can start small but if it improves and is useful it can quickly gain momentum, we had the first run, that was the introduction, the "hello world" so to speak, may be we can discuss where are we focusing on for the coming second round?

**Comment by trentmc** [comment]
We often discuss topics like this in the standup. It's ongoing. Closing this issue.
