### ISSUE TITLE
Make sure that the modules and readmes work for Windows systems

### ISSUE THREAD

**Issue by juanpablovs** [oceanprotocol/predict-eth#23]
There are a few tweaks that are relatively easy to implement so that Windows users can participate without any hassle.

3 examples:
1. Environment variable: set REMOTE_TEST_PRIVATE_KEY1=<your Polygon private key>
2. These commands have to be executed one after the other
    ocean = create_ocean_instance()
    alice_wallet = create_alice_wallet(ocean) #you're Alice
3. pybundlr fails because of raw strings

These are all small things that make sure that we are not neglecting a significant portion of the market that otherwise might find themselves stuck at the very beginning of the contest

**Comment by trentmc** [comment]
Hey @juanpablovs I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/predict-eth-637254d9b060b59d1ad67628/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_
