### ISSUE TITLE
nmse values are too small

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#38]
**Describe the bug**

Here's the current nmse function: ([here](https://github.com/oceanprotocol/predict-eth/blob/main/challenges/main2.md))

```python
def calc_nmse(y, yhat) -> float:
    assert len(y) == len(yhat)
    mse_xy = np.sum(np.square(np.asarray(y) - np.asarray(yhat)))
    mse_x = np.sum(np.square(np.asarray(y)))
    nmse = mse_xy / mse_x
    return nmse
```

On this, we would get test nmse values like 0.0000907 (0.00907%) or 0.00042637 (0.042637%). Yet in eyeballing the predictions, we expect error to be 20% - 50%. 

The likely culprit: denominator is too big.

**TODOs**

- [ ] Fix bug in predict-eth-judge repo, testing against Web3 ATL hackathon values
- [ ] Copy & paste the solution into predict-eth, to replace each instance of calc_nmse

**Comment by jfdelgad** [comment]
One more comment on this is that given the 12 hours period and the current variability of the ether price and error of 50% is significantly high, notice that is measured as described above this means that if in average in every hour the method predicts the price of ether to be half of what the real value is. Using data of the latest week, a method that just assign the to the 12 hours the latest seen value or the average of the latest 12 hours will have a significantly lower error compared to the expected 50% error, a quick calculation shows an error of about ~3% using the mean of the data from last week to predict the price today.
