### ISSUE TITLE
Update READMEs to reflect oceanpy#1095 changes (streamlined READMEs)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#81]
oceanpy#1095 having [this PR](https://github.com/oceanprotocol/ocean.py/pull/1148) revamped the ocean.py READMEs. This includes wholly new READMEs for local & remote setup, and a revamped install.md.

TODO here: ensure that predict-eth's READMEs work
- main3.md
- each end-to-end example
- any other non-obsolete READMEs. (main1, atl hackathon, main2 are obsolete, don't bother updating them)

**Comment by AnaLoznianu** [comment]
One issue we need to address is this error when creating the ocean instance: 
"  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in create_ocean_instance
NameError: name 'ExampleConfig' is not defined"
