### ISSUE TITLE
Make a video of how to submit (random) predictions. Why: maximize chance of successful submission

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#82]
### Background / motivation

Overall goal: Maximize chance of a successful submission. (Ideas issue: [#77](https://github.com/oceanprotocol/predict-eth/issues/77))

Many people learn best by video.

People don't stumble creating models; they stumble in steps of the submission flow (as # 77 discusses). So we want to focus the video on steps of the flow, and not on models. How: random predictions (as main3.md has).

### TODO for this issue

Create a video of how to submit random predictions (pred_vals). 

This basically means going through main3.md README, via a video.

Good lead-up videos: 1+ videos on using brownie, 1+ videos on using ocean.py.

**Comment by trentmc** [comment]
cc @AnaLoznianu - as discussed

**Comment by AnaLoznianu** [comment]
Thanks @trentmc! This is already on @graceful-coder pipe 👍

**Comment by AnaLoznianu** [comment]
Hey @graceful-coder I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/predict-eth-637254d9b060b59d1ad67628/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by trentmc** [comment]
@graceful-coder was this completed in round 3?

Though, for round 4 we're gonna want to do a new one, since the flow will be simpler. So perhaps let's leave this github issue open to ensure that it's done.

**Comment by trentmc** [comment]
Folded into: https://github.com/oceanprotocol/ocean.py/issues/1351
