### ISSUE TITLE
Boken link in Readme for predict-eth round 3

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/predict-eth#86]
Link provided in chapter 1.3 of the Readme document for predict-eth round 3 is broken. Here's the sample from the document:

"1.3 Create Mumbai Account (One-Time)
You'll be using Mumbai network (Polygon testnet).

In ocean.py's [get-test-MATIC.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/get-test-MATIC.md), follow all directions."

The link should point to https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/setup-remote.md#4-get-fake-ocean-on-mumbai

**Comment by jfdelgad** [comment]
Notice that the correct link is https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/setup-remote.md#3-get-fake-matic-on-mumbai which explains how to obtain matic testnet
