### ISSUE TITLE
Publish asset: btc/usdt on Ocean CEXA, into Polygon

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/predict-eth#9]
- [x] Publish asset: btc/usdt on Ocean CEXA, into Polygon. Example: [eth/usdt on Ocean CEXA](https://market.oceanprotocol.com/asset/did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19). 
- [ ] Update eth-predict2.md to also load it

Parent epic: https://github.com/oceanprotocol/predict-eth/issues/3

**Comment by AnaLoznianu** [comment]
The CEXA asset is published here: https://market.oceanprotocol.com/asset/did:op:b4584760f5133b27d91c337b9c10b56448b84a1bae39b8c1037d0de33023b4dc 
The data retrieved by the CEXA is currently not what we need, the PR to fix this is available here: https://github.com/oceanprotocol/cex_aggregator/pull/2

**Comment by AnaLoznianu** [comment]
@juanpablovs We fixed the cexa aggregator and now the asset: https://market.oceanprotocol.com/asset/did:op:b4584760f5133b27d91c337b9c10b56448b84a1bae39b8c1037d0de33023b4dc returns the latest 1000 values/hour.
Please take this issue over and update updated the eth-predict2 with this new asset
