### ISSUE TITLE
Replace create_url_asset instructions with create_arweave_asset

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/predict-eth#93]
At this moment, we are giving instructions to create an URL asset with the arweave file they uploaded, but we do have a function that creates and uploads the file as an arweave file: [create_arweave_asset](https://github.com/oceanprotocol/ocean.py/blob/6efaaa0dbf861baccb15c1e65f432e8605efca5c/ocean_lib/ocean/ocean_assets.py#L192).

**Comment by AnaLoznianu** [comment]
@jfdelgad Can you please take this? Thanks 

cc @trentmc

**Comment by jfdelgad** [comment]
> @jfdelgad Can you please take this? Thanks
> 
> cc @trentmc

I will take a look at this.

**Comment by jfdelgad** [comment]
@AnaLoznianu I do not think this is a good idea. The function [create_arweave_asset](https://github.com/oceanprotocol/ocean.py/blob/6efaaa0dbf861baccb15c1e65f432e8605efca5c/ocean_lib/ocean/ocean_assets.py#L192). requires the transaction id for the file, which in the current readme is done directly on the website. We will need to write more code to explain how to do this using python which I think it makes things more confuse.

**Comment by AnaLoznianu** [comment]
Thank you @jfdelgad for looking over this :) If it adds more complexity, let's ignore it for now.

**Comment by trentmc** [comment]
Good assessment Jaime. I agree. 

@AnaLoznianu did you mean to close the issue? (I would suggest yes, the priority for this is sufficiently low that I don't see us ever getting to it.)
